ALTER TABLE PRODUCTO
ADD COLUMN IF NOT EXISTS ESTADO VARCHAR(20) NOT NULL DEFAULT 'ACTIVO';

UPDATE PRODUCTO
SET ESTADO = 'ACTIVO'
WHERE ESTADO IS NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_producto_estado'
    ) THEN
        ALTER TABLE PRODUCTO
        ADD CONSTRAINT CK_PRODUCTO_ESTADO
        CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'));
    END IF;
END $$;
