ALTER TABLE VARIANTES_PRODUCTO
ADD COLUMN IF NOT EXISTS ESTADO VARCHAR(20) NOT NULL DEFAULT 'ACTIVO';

UPDATE VARIANTES_PRODUCTO
SET ESTADO = 'ACTIVO'
WHERE ESTADO IS NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_variante_producto_estado'
    ) THEN
        ALTER TABLE VARIANTES_PRODUCTO
        ADD CONSTRAINT CK_VARIANTE_PRODUCTO_ESTADO
        CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'));
    END IF;
END $$;
