CREATE TABLE IF NOT EXISTS IMAGENES_VARIANTE_PRODUCTO (
    ID_IMAGEN_VARIANTE INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_VARIANTE INTEGER NOT NULL,

    URL VARCHAR(500) NOT NULL,
    ALT_TEXT VARCHAR(200),
    ES_PRINCIPAL BOOLEAN NOT NULL DEFAULT FALSE,
    ORDEN INTEGER NOT NULL DEFAULT 0,
    ESTADO VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_IMAGENES_VARIANTE_PRODUCTO
        PRIMARY KEY (ID_IMAGEN_VARIANTE),

    CONSTRAINT CK_IMAGEN_VARIANTE_PRODUCTO_ESTADO
        CHECK (ESTADO IN ('ACTIVO', 'INACTIVO')),

    CONSTRAINT CK_IMAGEN_VARIANTE_PRODUCTO_ORDEN
        CHECK (ORDEN >= 0),

    CONSTRAINT FK_IMAGEN_VARIANTE
        FOREIGN KEY (ID_VARIANTE)
        REFERENCES VARIANTES_PRODUCTO(ID_VARIANTE)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_IMAGEN_VARIANTE
ON IMAGENES_VARIANTE_PRODUCTO(ID_VARIANTE);
