CREATE TABLE IF NOT EXISTS IMAGENES_PRODUCTO (
    ID_IMAGEN INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_PRODUCTO INTEGER NOT NULL,

    URL VARCHAR(500) NOT NULL,
    ALT_TEXT VARCHAR(200),
    ES_PRINCIPAL BOOLEAN NOT NULL DEFAULT FALSE,
    ORDEN INTEGER NOT NULL DEFAULT 0,
    ESTADO VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_IMAGENES_PRODUCTO
        PRIMARY KEY (ID_IMAGEN),

    CONSTRAINT CK_IMAGEN_PRODUCTO_ESTADO
        CHECK (ESTADO IN ('ACTIVO', 'INACTIVO')),

    CONSTRAINT CK_IMAGEN_PRODUCTO_ORDEN
        CHECK (ORDEN >= 0),

    CONSTRAINT FK_IMAGEN_PRODUCTO
        FOREIGN KEY (ID_PRODUCTO)
        REFERENCES PRODUCTO(ID_PRODUCTO)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_IMAGEN_PRODUCTO
ON IMAGENES_PRODUCTO(ID_PRODUCTO);
