CREATE TABLE IF NOT EXISTS ENVIOS (
    ID_ENVIO INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_PEDIDO INTEGER NOT NULL UNIQUE,

    TRANSPORTADORA VARCHAR(120),
    NUMERO_GUIA VARCHAR(120) UNIQUE,
    ESTADO VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',

    NOMBRE_DESTINATARIO VARCHAR(200) NOT NULL,
    CELULAR_DESTINATARIO VARCHAR(20),
    DIRECCION TEXT NOT NULL,
    CIUDAD VARCHAR(100) NOT NULL,
    DEPARTAMENTO VARCHAR(100),
    CODIGO_POSTAL VARCHAR(20),
    NOTAS TEXT,

    COSTO NUMERIC(12,2) NOT NULL DEFAULT 0,
    FECHA_DESPACHO TIMESTAMP,
    FECHA_ENTREGA TIMESTAMP,
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_ENVIOS
        PRIMARY KEY (ID_ENVIO),

    CONSTRAINT CK_ENVIOS_ESTADO
        CHECK (ESTADO IN (
            'PENDIENTE',
            'PREPARANDO',
            'DESPACHADO',
            'EN_TRANSITO',
            'ENTREGADO',
            'DEVUELTO',
            'CANCELADO'
        )),

    CONSTRAINT CK_ENVIOS_COSTO
        CHECK (COSTO >= 0),

    CONSTRAINT FK_ENVIOS_PEDIDO
        FOREIGN KEY (ID_PEDIDO)
        REFERENCES PEDIDO(ID_PEDIDO)
        ON DELETE CASCADE
);
