-- ==========================================
-- CATEGORIA
-- ==========================================
CREATE TABLE CATEGORIA (
    ID_CATEGORIA INTEGER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,

    CONSTRAINT PK_CATEGORIA
        PRIMARY KEY (ID_CATEGORIA)
);

-- ==========================================
-- PRODUCTO
-- ==========================================
CREATE TABLE PRODUCTO (
    ID_PRODUCTO INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_CATEGORIA INTEGER NOT NULL,

    NOMBRE VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,

    PAQUETE_ESTATICO BOOLEAN DEFAULT FALSE,

    CONSTRAINT PK_PRODUCTO
        PRIMARY KEY (ID_PRODUCTO),

    CONSTRAINT FK_PRODUCTO_CATEGORIA
        FOREIGN KEY (ID_CATEGORIA)
        REFERENCES CATEGORIA(ID_CATEGORIA)
);

-- ==========================================
-- VARIANTES_PRODUCTO
-- ==========================================
CREATE TABLE VARIANTES_PRODUCTO (
    ID_VARIANTE INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_PRODUCTO INTEGER NOT NULL,

    PRECIO_COSTO NUMERIC(12,2) NOT NULL,
    PRECIO_MINORISTA NUMERIC(12,2) NOT NULL,
    PRECIO_MAYORISTA NUMERIC(12,2) NOT NULL,

    PESO NUMERIC(10,2),

    APLICA_PAQUETE BOOLEAN DEFAULT FALSE,

    ATRIBUTOS JSONB,

    CONSTRAINT PK_VARIANTES_PRODUCTO
        PRIMARY KEY (ID_VARIANTE),

    CONSTRAINT FK_VARIANTE_PRODUCTO
        FOREIGN KEY (ID_PRODUCTO)
        REFERENCES PRODUCTO(ID_PRODUCTO)
);

-- ==========================================
-- CLIENTES
-- ==========================================
CREATE TABLE CLIENTES (
    ID_CLIENTE INTEGER GENERATED ALWAYS AS IDENTITY,

    CELULAR VARCHAR(20) UNIQUE,
    NOMBRE VARCHAR(200) NOT NULL,

    CONSTRAINT PK_CLIENTES
        PRIMARY KEY (ID_CLIENTE)
);

-- ==========================================
-- PEDIDO
-- ==========================================
CREATE TABLE PEDIDO (
    ID_PEDIDO INTEGER GENERATED ALWAYS AS IDENTITY,

    ID_CLIENTE INTEGER NOT NULL,

    ESTADO VARCHAR(30) NOT NULL,

    TOTAL NUMERIC(14,2) DEFAULT 0,

    PRECIO_ENVIO NUMERIC(12,2) DEFAULT 0,

    ES_MAYORISTA BOOLEAN DEFAULT FALSE,

    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_PEDIDO
        PRIMARY KEY (ID_PEDIDO),

    CONSTRAINT FK_PEDIDO_CLIENTE
        FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTES(ID_CLIENTE)
);

-- ==========================================
-- ITEMS_PEDIDO
-- ==========================================
CREATE TABLE ITEMS_PEDIDO (
    ID_ITEM_PEDIDO INTEGER GENERATED ALWAYS AS IDENTITY,

    ID_PEDIDO INTEGER NOT NULL,
    ID_VARIANTE INTEGER NOT NULL,

    CANTIDAD INTEGER NOT NULL,

    PRECIO_UNITARIO NUMERIC(12,2) NOT NULL,

    CONSTRAINT PK_ITEMS_PEDIDO
        PRIMARY KEY (ID_ITEM_PEDIDO),

    CONSTRAINT CK_ITEMS_CANTIDAD
        CHECK (CANTIDAD > 0),

    CONSTRAINT FK_ITEMS_PEDIDO
        FOREIGN KEY (ID_PEDIDO)
        REFERENCES PEDIDO(ID_PEDIDO)
        ON DELETE CASCADE,

    CONSTRAINT FK_ITEMS_VARIANTE
        FOREIGN KEY (ID_VARIANTE)
        REFERENCES VARIANTES_PRODUCTO(ID_VARIANTE)
);

-- ==========================================
-- PAQUETES_ESTATICOS_ITEMS
-- ==========================================
CREATE TABLE PAQUETES_ESTATICOS_ITEMS (
    ID_PAQUETE INTEGER NOT NULL,
    ID_VARIANTE INTEGER NOT NULL,

    CANTIDAD INTEGER NOT NULL,

    CONSTRAINT PK_PAQUETES_ESTATICOS_ITEMS
        PRIMARY KEY (ID_PAQUETE, ID_VARIANTE),

    CONSTRAINT CK_PAQUETE_CANTIDAD
        CHECK (CANTIDAD > 0),

    CONSTRAINT FK_PAQUETE_PRODUCTO
        FOREIGN KEY (ID_PAQUETE)
        REFERENCES PRODUCTO(ID_PRODUCTO)
        ON DELETE CASCADE,

    CONSTRAINT FK_PAQUETE_VARIANTE
        FOREIGN KEY (ID_VARIANTE)
        REFERENCES VARIANTES_PRODUCTO(ID_VARIANTE)
        ON DELETE CASCADE
);

-- ==========================================
-- INDICES
-- ==========================================

CREATE INDEX IDX_PRODUCTO_CATEGORIA
ON PRODUCTO(ID_CATEGORIA);

CREATE INDEX IDX_VARIANTE_PRODUCTO
ON VARIANTES_PRODUCTO(ID_PRODUCTO);

CREATE INDEX IDX_PEDIDO_CLIENTE
ON PEDIDO(ID_CLIENTE);

CREATE INDEX IDX_ITEMS_PEDIDO
ON ITEMS_PEDIDO(ID_PEDIDO);

CREATE INDEX IDX_ITEMS_VARIANTE
ON ITEMS_PEDIDO(ID_VARIANTE);

CREATE INDEX IDX_PAQUETE_VARIANTE
ON PAQUETES_ESTATICOS_ITEMS(ID_VARIANTE);