-- ==========================================
-- USUARIOS
-- ==========================================
CREATE TABLE USUARIOS (
    ID_USUARIO INTEGER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(160) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ROL VARCHAR(30) NOT NULL DEFAULT 'ADMINISTRADOR',
    ACTIVO BOOLEAN NOT NULL DEFAULT TRUE,
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ULTIMO_ACCESO TIMESTAMP,

    CONSTRAINT PK_USUARIOS
        PRIMARY KEY (ID_USUARIO),

    CONSTRAINT CK_USUARIOS_ROL
        CHECK (ROL = 'ADMINISTRADOR')
);

-- ==========================================
-- CATEGORIA
-- ==========================================
CREATE TABLE CATEGORIA (
    ID_CATEGORIA INTEGER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,

    CONSTRAINT PK_CATEGORIA
        PRIMARY KEY (ID_CATEGORIA)
);

-- ==========================================
-- PRODUCTO
-- ==========================================
CREATE TABLE PRODUCTO (
    ID_PRODUCTO INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_CATEGORIA INTEGER NOT NULL,

    NOMBRE VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,

    PAQUETE_ESTATICO BOOLEAN DEFAULT FALSE,
    ESTADO VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',

    CONSTRAINT PK_PRODUCTO
        PRIMARY KEY (ID_PRODUCTO),

    CONSTRAINT CK_PRODUCTO_ESTADO
        CHECK (ESTADO IN ('ACTIVO', 'INACTIVO')),

    CONSTRAINT FK_PRODUCTO_CATEGORIA
        FOREIGN KEY (ID_CATEGORIA)
        REFERENCES CATEGORIA(ID_CATEGORIA)
);

-- ==========================================
-- VARIANTES_PRODUCTO
-- ==========================================
CREATE TABLE VARIANTES_PRODUCTO (
    ID_VARIANTE INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_PRODUCTO INTEGER NOT NULL,

    PRECIO_COSTO NUMERIC(12,2) NOT NULL,
    PRECIO_MINORISTA NUMERIC(12,2) NOT NULL,
    PRECIO_MAYORISTA NUMERIC(12,2) NOT NULL,

    PESO NUMERIC(10,2),

    APLICA_PAQUETE BOOLEAN DEFAULT FALSE,

    ATRIBUTOS JSONB,
    ESTADO VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',

    CONSTRAINT PK_VARIANTES_PRODUCTO
        PRIMARY KEY (ID_VARIANTE),

    CONSTRAINT CK_VARIANTE_PRODUCTO_ESTADO
        CHECK (ESTADO IN ('ACTIVO', 'INACTIVO')),

    CONSTRAINT FK_VARIANTE_PRODUCTO
        FOREIGN KEY (ID_PRODUCTO)
        REFERENCES PRODUCTO(ID_PRODUCTO)
);

-- ==========================================
-- IMAGENES_PRODUCTO
-- ==========================================
CREATE TABLE IMAGENES_PRODUCTO (
    ID_IMAGEN INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_PRODUCTO INTEGER NOT NULL,

    URL VARCHAR(500) NOT NULL,
    ALT_TEXT VARCHAR(200),
    ES_PRINCIPAL BOOLEAN NOT NULL DEFAULT FALSE,
    ORDEN INTEGER NOT NULL DEFAULT 0,
    ESTADO VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_IMAGENES_PRODUCTO
        PRIMARY KEY (ID_IMAGEN),

    CONSTRAINT CK_IMAGEN_PRODUCTO_ESTADO
        CHECK (ESTADO IN ('ACTIVO', 'INACTIVO')),

    CONSTRAINT CK_IMAGEN_PRODUCTO_ORDEN
        CHECK (ORDEN >= 0),

    CONSTRAINT FK_IMAGEN_PRODUCTO
        FOREIGN KEY (ID_PRODUCTO)
        REFERENCES PRODUCTO(ID_PRODUCTO)
        ON DELETE CASCADE
);

-- ==========================================
-- IMAGENES_VARIANTE_PRODUCTO
-- ==========================================
CREATE TABLE IMAGENES_VARIANTE_PRODUCTO (
    ID_IMAGEN_VARIANTE INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_VARIANTE INTEGER NOT NULL,

    URL VARCHAR(500) NOT NULL,
    ALT_TEXT VARCHAR(200),
    ES_PRINCIPAL BOOLEAN NOT NULL DEFAULT FALSE,
    ORDEN INTEGER NOT NULL DEFAULT 0,
    ESTADO VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_IMAGENES_VARIANTE_PRODUCTO
        PRIMARY KEY (ID_IMAGEN_VARIANTE),

    CONSTRAINT CK_IMAGEN_VARIANTE_PRODUCTO_ESTADO
        CHECK (ESTADO IN ('ACTIVO', 'INACTIVO')),

    CONSTRAINT CK_IMAGEN_VARIANTE_PRODUCTO_ORDEN
        CHECK (ORDEN >= 0),

    CONSTRAINT FK_IMAGEN_VARIANTE
        FOREIGN KEY (ID_VARIANTE)
        REFERENCES VARIANTES_PRODUCTO(ID_VARIANTE)
        ON DELETE CASCADE
);

-- ==========================================
-- CLIENTES
-- ==========================================
CREATE TABLE CLIENTES (
    ID_CLIENTE INTEGER GENERATED ALWAYS AS IDENTITY,

    CELULAR VARCHAR(20) UNIQUE,
    NOMBRE VARCHAR(200) NOT NULL,

    CONSTRAINT PK_CLIENTES
        PRIMARY KEY (ID_CLIENTE)
);

-- ==========================================
-- PEDIDO
-- ==========================================
CREATE TABLE PEDIDO (
    ID_PEDIDO INTEGER GENERATED ALWAYS AS IDENTITY,

    ID_CLIENTE INTEGER NOT NULL,

    ESTADO VARCHAR(30) NOT NULL,

    TOTAL NUMERIC(14,2) DEFAULT 0,

    PRECIO_ENVIO NUMERIC(12,2) DEFAULT 0,

    ES_MAYORISTA BOOLEAN DEFAULT FALSE,

    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_PEDIDO
        PRIMARY KEY (ID_PEDIDO),

    CONSTRAINT FK_PEDIDO_CLIENTE
        FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTES(ID_CLIENTE)
);

-- ==========================================
-- ENVIOS
-- ==========================================
CREATE TABLE ENVIOS (
    ID_ENVIO INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_PEDIDO INTEGER NOT NULL UNIQUE,

    TRANSPORTADORA VARCHAR(120),
    NUMERO_GUIA VARCHAR(120) UNIQUE,
    ESTADO VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',

    NOMBRE_DESTINATARIO VARCHAR(200) NOT NULL,
    CELULAR_DESTINATARIO VARCHAR(20),
    DIRECCION TEXT NOT NULL,
    CIUDAD VARCHAR(100) NOT NULL,
    DEPARTAMENTO VARCHAR(100),
    CODIGO_POSTAL VARCHAR(20),
    NOTAS TEXT,

    COSTO NUMERIC(12,2) NOT NULL DEFAULT 0,
    FECHA_DESPACHO TIMESTAMP,
    FECHA_ENTREGA TIMESTAMP,
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_ENVIOS
        PRIMARY KEY (ID_ENVIO),

    CONSTRAINT CK_ENVIOS_ESTADO
        CHECK (ESTADO IN (
            'PENDIENTE',
            'PREPARANDO',
            'DESPACHADO',
            'EN_TRANSITO',
            'ENTREGADO',
            'DEVUELTO',
            'CANCELADO'
        )),

    CONSTRAINT CK_ENVIOS_COSTO
        CHECK (COSTO >= 0),

    CONSTRAINT FK_ENVIOS_PEDIDO
        FOREIGN KEY (ID_PEDIDO)
        REFERENCES PEDIDO(ID_PEDIDO)
        ON DELETE CASCADE
);

-- ==========================================
-- ITEMS_PEDIDO
-- ==========================================
CREATE TABLE ITEMS_PEDIDO (
    ID_ITEM_PEDIDO INTEGER GENERATED ALWAYS AS IDENTITY,

    ID_PEDIDO INTEGER NOT NULL,
    ID_VARIANTE INTEGER NOT NULL,

    CANTIDAD INTEGER NOT NULL,

    PRECIO_UNITARIO NUMERIC(12,2) NOT NULL,

    CONSTRAINT PK_ITEMS_PEDIDO
        PRIMARY KEY (ID_ITEM_PEDIDO),

    CONSTRAINT CK_ITEMS_CANTIDAD
        CHECK (CANTIDAD > 0),

    CONSTRAINT FK_ITEMS_PEDIDO
        FOREIGN KEY (ID_PEDIDO)
        REFERENCES PEDIDO(ID_PEDIDO)
        ON DELETE CASCADE,

    CONSTRAINT FK_ITEMS_VARIANTE
        FOREIGN KEY (ID_VARIANTE)
        REFERENCES VARIANTES_PRODUCTO(ID_VARIANTE)
);

-- ==========================================
-- PAQUETES_ESTATICOS_ITEMS
-- ==========================================
CREATE TABLE PAQUETES_ESTATICOS_ITEMS (
    ID_PAQUETE INTEGER NOT NULL,
    ID_VARIANTE INTEGER NOT NULL,

    CANTIDAD INTEGER NOT NULL,

    CONSTRAINT PK_PAQUETES_ESTATICOS_ITEMS
        PRIMARY KEY (ID_PAQUETE, ID_VARIANTE),

    CONSTRAINT CK_PAQUETE_CANTIDAD
        CHECK (CANTIDAD > 0),

    CONSTRAINT FK_PAQUETE_PRODUCTO
        FOREIGN KEY (ID_PAQUETE)
        REFERENCES PRODUCTO(ID_PRODUCTO)
        ON DELETE CASCADE,

    CONSTRAINT FK_PAQUETE_VARIANTE
        FOREIGN KEY (ID_VARIANTE)
        REFERENCES VARIANTES_PRODUCTO(ID_VARIANTE)
        ON DELETE CASCADE
);

-- ==========================================
-- INDICES
-- ==========================================

CREATE INDEX IDX_PRODUCTO_CATEGORIA
ON PRODUCTO(ID_CATEGORIA);

CREATE INDEX IDX_VARIANTE_PRODUCTO
ON VARIANTES_PRODUCTO(ID_PRODUCTO);

CREATE INDEX IDX_IMAGEN_PRODUCTO
ON IMAGENES_PRODUCTO(ID_PRODUCTO);

CREATE INDEX IDX_IMAGEN_VARIANTE
ON IMAGENES_VARIANTE_PRODUCTO(ID_VARIANTE);

CREATE INDEX IDX_PEDIDO_CLIENTE
ON PEDIDO(ID_CLIENTE);

CREATE INDEX IDX_ITEMS_PEDIDO
ON ITEMS_PEDIDO(ID_PEDIDO);

CREATE INDEX IDX_ITEMS_VARIANTE
ON ITEMS_PEDIDO(ID_VARIANTE);

CREATE INDEX IDX_PAQUETE_VARIANTE
ON PAQUETES_ESTATICOS_ITEMS(ID_VARIANTE);
